### ISSUE TITLE
Just bought, how do i switch pages?

### ISSUE THREAD

**Issue by AjaxFNC-YT** [Akascape/CTkDesigner-Support#18]
i saw a comment on youtube saying to switch pages, how do you do that?
Also, love the app <3

**Comment by AjaxFNC-YT** [comment]
never mind,  for anyone with same question, right click a button or something and do "add navigation" and select the page

**Comment by Akascape** [comment]
@AjaxFNC-YT Sorry for the late reply, yes we can switch page with the buttons and the 'add navigation' option. 

Thanks for your support :)
