### ISSUE TITLE
Add a "preview" option

### ISSUE THREAD

**Issue by AjaxFNC-YT** [Akascape/CTkDesigner-Support#19]
I have stuff that switches the page, but i cant test it without exporting as py. u should add a "preview" option to just run the file

also possibly a "open .py" instead of .json, saving json then exporting py is kinda just annoying

**Comment by Akascape** [comment]
Ok, I will try to add this in next version.

**Comment by Akascape** [comment]
@AjaxFNC-YT Added the option in v6.0

**Comment by AjaxFNC-YT** [comment]
yo, u should add a way to select mutipule items and manage them, like delete muti, edit muti, and duplicate muti, when dupiclating it should allow u to move both of them

**Comment by AjaxFNC-YT** [comment]
also a way to enter a video for the video widget

**Comment by Akascape** [comment]
@AjaxFNC-YT Selecting multiple widgets will be tough to implement. 

Secondly, if I add the ability to add video then I have to pack the pyav module which is >50mb in size. It will increase the exe size, so that's why I have not implemented it. But you can add your video easily in the widget through code.

**Comment by AjaxFNC-YT** [comment]
alr, could you add a image widget?

**Comment by AjaxFNC-YT** [comment]
ok, thank you, could u add a undo option?

**Comment by Akascape** [comment]
@AjaxFNC-YT Will work on the undo option.

**Comment by AjaxFNC-YT** [comment]
Hello, is there an update for the undo option?
alos i have another suggestion, could you add snaplines the widgets (so i can snap them to the center) just like a image editor would have?

**Comment by AjaxFNC-YT** [comment]
any updates?
V6 works good, but its kinda buggy

**Comment by AjaxFNC-YT** [comment]
im gonna use V5 again, V6 is good and has good features, but dam, its annoying with the bugs, for example, i change a color on a object, and next thing you know, i click off of it, and it goes back to what it was before. very annoying while tryna make GUIs.

**Comment by Akascape** [comment]
>for example, i change a color on a object, and next thing you know, i click off of it, and it goes back to what it was before. very annoying while tryna make GUIs.

@AjaxFNC-YT Can you further explain this bug? Like some screenshot

**Comment by AjaxFNC-YT** [comment]
Here is a view of me showing it

Idk if it showcases it well, but i hope it does.

https://github.com/user-attachments/assets/bd4f96b5-29f7-44de-8372-da2565c5dc06

**Comment by AjaxFNC-YT** [comment]
also another issue ive been having, most of the time the preview button just doesnt work/do anything when i press it

**Comment by Akascape** [comment]
@AjaxFNC-YT Ok, the first is behavior is happening because the bg_color is automatically set to the background frame color. You can fix that widget in frame after changing the bg_color. Or change the fg_color as its a label, it's not actually a bug. 

> also another issue ive been having, most of the time the preview button just doesnt work/do anything when i press it

You have to properly install the modules in the python version, check which version you have as the default python in your environment variable, the preview option directly runs the files on the default python version.

**Comment by AjaxFNC-YT** [comment]
And for the preview button not working?

**Comment by AjaxFNC-YT** [comment]
Also I should be able to turn that off, u should make it a setting where it automatically does that or not

**Comment by Akascape** [comment]
> also another issue ive been having, most of the time the preview button just doesnt work/do anything when i press it

@AjaxFNC-YT You may be using a different python version when you preview it, because the modules are not installed in that version.  You have to change it to correct python version, just move the version to top in environment variables of windows.

**Comment by Akascape** [comment]
@AjaxFNC-YT 
> Also I should be able to turn that off, u should make it a setting where it automatically does that or not

Yes, but why changing the bg_color of the label? There are already workarounds. bg_color should always camouflage with the background, that's how customtkinter widgets should work.

**Comment by AjaxFNC-YT** [comment]
for some reason its not, it takes the bg, but it should take the bg of the frame

**Comment by AjaxFNC-YT** [comment]
question.. what does V7 add?

**Comment by Akascape** [comment]
@AjaxFNC-YT Changelog for V7 is given here: https://github.com/Akascape/CTkDesigner-Support/discussions/26

**Comment by AjaxFNC-YT** [comment]
is there a way you could make the draw widget not make the corner radius not a circle and more like a corner like a button?

this is the circle thingy:

![image](https://github.com/user-attachments/assets/d1795a16-5988-49ae-be9e-a0f863b8af42)


it should only do the corners, not make it a circle:
kinda like this: ![image](https://github.com/user-attachments/assets/8d4a5b54-f869-44a3-a2e7-e4bd8e711eec)

idk if its possible to fix/add a option for, but, just thought i would say something, its kinda annoying, at the moment i have to make it a PNG and round it in another software, would be cool if i didnt have to do that. also ik CTRL + Z is expermental, but could you make the ctrl + z undo pastes (ctrl + v)

**Comment by Akascape** [comment]
@AjaxFNC-YT Ok, will add this soon.

**Comment by AjaxFNC-YT** [comment]
Will there he a 7.2?

**Comment by Akascape** [comment]
@AjaxFNC-YT Maybe not in 7.2, minor updates are provided when there are some major bugs in the version. New features are added in major versions, which I think is a good update plan/roadmap. But I can provide an update in ctkdlib, where I will add another feature to solve the problem you described. But it will be a manual parameter which you have to pass through the parameter box.

**Comment by AjaxFNC-YT** [comment]
please do.

**Comment by Akascape** [comment]
@AjaxFNC-YT Added a new parameter `balanced_corner`, you can set it to True to get equal corner radius instead of an oval.
For now, you have to manually add this line in the exported code, make sure to update ctkdlib to 7.1

**Comment by AjaxFNC-YT** [comment]
W!!!!!! Thank you for that, it looks so much better now. And i was able to add it in the actual app by passing balanced_corner=True then clicking preview

**Comment by AjaxFNC-YT** [comment]
Bug: the grid lines dont stay at the top, i can put a frame over it and it goes away.

**Comment by AjaxFNC-YT** [comment]
could you fix that?

**Comment by Akascape** [comment]
@AjaxFNC-YT Can you explain how it goes away? You are using the latest version right?

**Comment by AjaxFNC-YT** [comment]
im using latest version, i mean, if you put a frame (for example for a sidebar or something) the gird will be under the frame, it should be on top of all widgets

**Comment by Akascape** [comment]
@AjaxFNC-YT Yes I can fix it like that. Originally the idea was to keep it in top, but it was looking a little off for the placed widgets. But don't worry I will add a new option.
