### ISSUE TITLE
Bugs and requests in V6

### ISSUE THREAD

**Issue by teijiIshida** [Akascape/CTkDesigner-Support#23]
I was testing V6 and found some bugs....

Bug: when clicking Adjust Font, the label shows "Frame Size" instead of "Font Size". But after changing the font size, it then fixes itself.
Bug: With segmentedbutton, when Add Navigation (Auto). After I export .py, when I click the segementedbuttons, everything jumps all over the place.

I'll also make some suggestions too if you don't mind...
Feature request:
-Allow pages to be renamed and reordered. It's useful when using segmentedbutton if a user want to change their mind on which button link to which page.
-Remember locked status on re-open json. I locked all the widgets because I tend to accidentally move it a few pixel when double-click, but they get unlock every time I Open json again.

**Comment by Akascape** [comment]
@teijiIshida 
> when clicking Adjust Font, the label shows "Frame Size" instead of "Font Size".

Silly typo error, will be fixed.

> Bug: With segmentedbutton, when Add Navigation (Auto). After I export .py, when I click the segementedbuttons, everything jumps all over the place.

Did you fix the segmented button or not? 

Will work on these features later.

**Comment by teijiIshida** [comment]
Before, I had all the widgets on top frame, including segmented button, all Fixed Above, so they jump all over the place. After I fixed them all in frame, it works correctly now.  Thanks.

No problem. I'm glad you're taking suggestions.

**Comment by teijiIshida** [comment]
Bug: When clicking Save, if the filename has a dot, it will always ask for a new filename (just like Save As). For example, if my filename is config3.2.json, it will ask for a name every time I click Save.

**Comment by Akascape** [comment]
> I just found out if I fix the widgets to a frame

You have to click fix above to remove the widget from frame, then move it, then again click fix in frame.

> Can you make the tooltip closer to its widget?

I will try to improve the tooltip, if you want a different tooltip then you can use my [CTkTooltip](https://github.com/Akascape/CTkToolTip) widget whoch contains lots of other features. 

The point is that, you can edit everything in the code and get the desired results. But it takes time to write manually.

**Comment by teijiIshida** [comment]
Thank you. I just tried your CTkTooltip. It's amazing! I love the customization and professional look. Also, the placement was spot on without any x/y offset, justify, etc. I think the tooltip in CTkDesigner has a placement bug. 

This is an example of me placing my mouse cursor in the middle of the right textbox (right of TG Path button). CTkDesigner's tooltip shows it way off on top, while CTkTooltip shows it just to the right of the mouse cursor as one would expect.

Default tooltip from CTKDesigner:
![default tooltip](https://github.com/Akascape/CTkDesigner-Support/assets/33733459/986d7670-6086-4706-aae7-8004d3756732)

CTkTooltip:
![ctktooltip](https://github.com/Akascape/CTkDesigner-Support/assets/33733459/581909fe-e0da-4bb3-89be-d0cc063432ff)
