### ISSUE TITLE
Add font size value along with the slider

### ISSUE THREAD

**Issue by InfHorus** [Akascape/CTkDesigner-Support#5]
It is complicated to use the slider and prevent you from using the same size for every element, it would be a very good addition to have also the value on the side so we know what size we are currently using

**Comment by InfHorus** [comment]
Would also be a very nice addition for the image width & height slider to be able to see or edit the value directly

**Comment by Akascape** [comment]
@InfHorus Added the manual entry value option for all the slider:
![image](https://github.com/Akascape/CTkDesigner-Support/assets/89206401/884096d0-dd4f-4bff-862c-1d599046c159)

**Comment by Akascape** [comment]
@InfHorus 
> Would also be a very nice addition for the image width & height slider to be able to see or edit the value directly

Font and Image both are sub-categories of the widgets, so adding those in the same window may cause issues while saving.
