### ISSUE TITLE
Duplication of label with adjusted font size does not duplicate the font size

### ISSUE THREAD

**Issue by InfHorus** [Akascape/CTkDesigner-Support#6]
When duplicating a label with a custom font size the duplicate doesn't apply the font size and apply the default one

**Comment by Akascape** [comment]
@InfHorus Can you provide a screenshot after duplicating the label?

**Comment by InfHorus** [comment]
> @InfHorus Can you provide a screenshot after duplicating the label?

sure, 
<img width="513" alt="image" src="https://github.com/Akascape/CTkDesigner-Support/assets/46110121/b4b758a7-75c2-48ff-ae83-1a40fce3f272">
<img width="492" alt="image" src="https://github.com/Akascape/CTkDesigner-Support/assets/46110121/0ab3ac9c-dae4-4235-891b-37afbf3d75fd">
also another bug, the size doesn't save when exporting to .py, for example I saved a frame with a label and exported to .py, then it become small again 
<img width="315" alt="image" src="https://github.com/Akascape/CTkDesigner-Support/assets/46110121/e5831ba7-b3d9-40c8-9d9e-4c192a2cbc18">

**Comment by Akascape** [comment]
@InfHorus Ok thanks, I will work on this soon.

**Comment by InfHorus** [comment]
> @InfHorus Ok thanks, I will work on this soon.

Thanks!

**Comment by Akascape** [comment]
@InfHorus It is happening because the parameter window is closed without closing the font box (which is forced closed, and the font is not saved). But now its fixed.

**Comment by Akascape** [comment]
Fixed, download version 4.
