### ISSUE TITLE
Issue when making an element persistent with right click "Fix"

### ISSUE THREAD

**Issue by InfHorus** [Akascape/CTkDesigner-Support#7]
First problem is when making a header for your app, then persisting it using Fix, all new item we spawn get spawned below that header so that makes it just unusable at all.

<img width="674" alt="image" src="https://github.com/Akascape/CTkDesigner-Support/assets/46110121/bb8bfc41-9dc9-4bc1-a51a-16308c11637f">

Second problem when "Fixing" a label it reset its font properties like the size 
before:
<img width="669" alt="image" src="https://github.com/Akascape/CTkDesigner-Support/assets/46110121/a50a8896-dbf5-4d06-b96a-0deac96763d5">

after: 
<img width="672" alt="image" src="https://github.com/Akascape/CTkDesigner-Support/assets/46110121/15c04df1-6232-4dd0-8ead-7ec1f9a3b305">

overall the application is very cool it just has a lot of bugs, mainly on the Label element that makes it difficult to use, but once fixed the app would be a game changer

**Comment by Akascape** [comment]
@InfHorus Thanks for reporting these bugs, the next update should fix this. 

As it's in the early stage, there are some few bugs like this. But again, thanks for supporting this project.

**Comment by InfHorus** [comment]
> @InfHorus Thanks for reporting these bugs, the next update should fix this.
> 
> As it's in the early stage, there are some few bugs like this. But again, thanks for supporting this project.

Thanks, it has a huge potential with a few additions and bug fixes it could easily become one of the most used gui maker for python.

**Comment by InfHorus** [comment]
> @InfHorus Thanks for reporting these bugs, the next update should fix this.
> 
> As it's in the early stage, there are some few bugs like this. But again, thanks for supporting this project.

Do you think for next update you can also add a way to add images? From what I've seen right now if I want to add an image only I have to cheat by using a button and use empty char in it then merge the colors with the background, unless there is a better method I haven't seen

**Comment by InfHorus** [comment]
Also when using a label with the parameter "Italic" it clips the end of the word,
Before: 
<img width="178" alt="image" src="https://github.com/Akascape/CTkDesigner-Support/assets/46110121/a97666e0-3fb2-45e0-b405-6143b5aea329">

After Italic:
<img width="148" alt="image" src="https://github.com/Akascape/CTkDesigner-Support/assets/46110121/99233837-0e42-45b2-b81b-4474325386ec">


it does that whatever the word and the size of the text

**Comment by Akascape** [comment]
> Also when using a label with the parameter "Italic" it clips the end of the word,
@InfHorus Try adjusting the padx slider

**Comment by Akascape** [comment]
> > @InfHorus Thanks for reporting these bugs, the next update should fix this.
> > As it's in the early stage, there are some few bugs like this. But again, thanks for supporting this project.
> 
> Do you think for next update you can also add a way to add images? From what I've seen right now if I want to add an image only I have to cheat by using a button and use empty char in it then merge the colors with the background, unless there is a better method I haven't seen

@InfHorus The only way to add image is through label/button, still I can make a different widget but that will be same as the label one, just the text will be set to None.

**Comment by Akascape** [comment]
> Second problem when "Fixing" a label it reset its font properties like the size

@InfHorus Same as I mentioned, if the font box is not closed manually, then the font is not saved in the properties. But fixed now.

**Comment by Akascape** [comment]
@InfHorus 
> When adding images through a label, after export to .py: only one image is saved in the code file, and the image does not load correctly as it does not appear at all when running the code

Similar like font box, if you don't close the dialog box through the X button, then the changes are not saved internally. I guess you are directly closing the whole window by clicking outside the parameter window and that is causing that issue. But now it is fixed.

> When adding images through a button, very often then the button becomes unusable as it can't be deleted, nor moved, nor edited through property, its like the button does not respond anymore to anything. For instance it occured mainly when making the image inside the button bigger to take the whole button space

That's a issue with customtkinter core library, but I will solve it for ctk designer.

**Comment by Akascape** [comment]
@InfHorus 
> First problem is when making a header for your app, then persisting it using Fix, all new item we spawn get spawned below that header so that makes it just unusable at all.

This issue is also fixed now, the widgets will not spawn below fixed widgets.

**Comment by InfHorus** [comment]
> @InfHorus
> 
> > First problem is when making a header for your app, then persisting it using Fix, all new item we spawn get spawned below that header so that makes it just unusable at all.
> 
> This issue is also fixed now, the widgets will not spawn below fixed widgets.

Thanks for all these fixes, the software will be so much better, do you have any specific date for a new release? I can also "beta test" if required

**Comment by InfHorus** [comment]
> > > @InfHorus Thanks for reporting these bugs, the next update should fix this.
> > > As it's in the early stage, there are some few bugs like this. But again, thanks for supporting this project.
> > 
> > 
> > Do you think for next update you can also add a way to add images? From what I've seen right now if I want to add an image only I have to cheat by using a button and use empty char in it then merge the colors with the background, unless there is a better method I haven't seen
> 
> @InfHorus The only way to add image is through label/button, still I can make a different widget but that will be same as the label one, just the text will be set to None.

Maybe adding a canva for that could be cool? If i'm correct it allows to add image inside shapes so it would be useful in many scenario like for a user account image

**Comment by Akascape** [comment]
> Maybe adding a canva for that could be cool? If i'm correct it allows to add image inside shapes so it would be useful in many scenario like for a user account image

@InfHorus 

![image](https://github.com/Akascape/CTkDesigner-Support/assets/89206401/0bbcb6dd-0ec1-4c7c-90ee-8e4a7fca5890)
Added a new widget called CTkDraw, we can adjust corner radius, width, height of the image directly. Even we can adjust blur, contrast, brightness... and even draw on top of the canvas with mouse.

**Comment by InfHorus** [comment]
> > Maybe adding a canva for that could be cool? If i'm correct it allows to add image inside shapes so it would be useful in many scenario like for a user account image
> 
> @InfHorus
> 
> ![image](https://private-user-images.githubusercontent.com/89206401/311654476-0bbcb6dd-0ec1-4c7c-90ee-8e4a7fca5890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTAzNjgsIm5iZiI6MTcxMDE1MDA2OCwicGF0aCI6Ii84OTIwNjQwMS8zMTE2NTQ0NzYtMGJiY2I2ZGQtMGVjMS00YzdjLTkwZWUtOGU0YTdmY2E1ODkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA5NDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMGE1MzUzN2FmYTZjOGI0YWM4N2Y1NTJiNzBhMDAyYzkxMjExMTYwZjk5YjZiOGNkNDczNzY4MzNlMmYzMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SMnrAfsGwxuCpnS8gB8vP14WhgsRwVAYy7b212VetDs) Added a new widget called CTkDraw, we can adjust corner radius, width, height of the image directly. Even we can adjust blur, contrast, brightness... and even draw on top of the canvas with mouse.

That's very cool good job, slowly slowly I think it will become one of the best gui maker

**Comment by InfHorus** [comment]
> @InfHorus
> 
> > First problem is when making a header for your app, then persisting it using Fix, all new item we spawn get spawned below that header so that makes it just unusable at all.
> 
> This issue is also fixed now, the widgets will not spawn below fixed widgets.

Some minor bugs/improvement possible:
- When using a label with ' like for example don't or other words, the code errors because it writes the text using single quote, switching to double quote " would tackle the issue
- A way maybe to center an image in a button? As in we have left, right, top, bottom. not sure if its worth it for the moment as a bypass I just pass the arg text="" and put the image on right but it seem slightly off, not too sure

**Comment by InfHorus** [comment]
> > @InfHorus
> > > First problem is when making a header for your app, then persisting it using Fix, all new item we spawn get spawned below that header so that makes it just unusable at all.
> > 
> > 
> > This issue is also fixed now, the widgets will not spawn below fixed widgets.
> 
> Some minor bugs/improvement possible:
> 
> * When using a label with ' like for example don't or other words, the code errors because it writes the text using single quote, switching to double quote " would tackle the issue
> * A way maybe to center an image in a button? As in we have left, right, top, bottom. not sure if its worth it for the moment as a bypass I just pass the arg text="" and put the image on right but it seem slightly off, not too sure

Also seen the next roadmap it's very good additions especially the tooltips! for future updates a treeview support would be a very nice addition as well

**Comment by InfHorus** [comment]
> @InfHorus Tooltip is ready, working on menu popup, 3 new widget added: ctkdraw, ctkgif and ctkvideo. plus all the issues you mentioned are almost fixed.
> 
> Will release the next version soon.

Very great work, can't wait to test it out

**Comment by Akascape** [comment]
> Very great work, can't wait to test it out
@InfHorus Version 4 is here!

**Comment by InfHorus** [comment]
> > Very great work, can't wait to test it out
> 
> @InfHorus Version 4 is released!

Cool! Where do I download it? On Ko-fi I can't manage to find a way to download the new version as I already bought the version 3 recently
